---

- name: Remove unneeded filesystem kernel module
  modprobe:
    name:  "{{ item }}"
    state: absent
  with_items: "{{ os_hardening_fs_modules_disable }}"
  tags: [ filesystem ]

- name: Disable mounting of unneeded filesystems
  template:
    src:  modules-disable.conf.j2
    dest: /etc/modprobe.d/CIS.conf
    owner: root
    group: root
    mode: 0644
  tags: [ filesystem ]

- debug: msg='1.1.2 - 1.1.19 | Not Implemented as they relate to filesystem partitions and mount options'

- name: Set the sticky bit on all world writable directories | 1.1.20
  shell: >
      df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d -perm -0002 2>/dev/null | xargs chmod a+t
  tags: [ filesystem ]

- name: Check if /etc/init/autofs.conf exists
  stat:
    path: /etc/init/autofs.conf
  register: autofs

- name: Comment out start lines in /etc/init/autofs.conf | 1.1.21
  lineinfile:
    path: /etc/init/autofs.conf
    regexp: '^start on runlevel'
    line: '#start on runlevel [2345]'
  when: autofs.stat.exists
