---

# ensure inetd is not installed
# ensure xinetd is not installed

- name: Uninstall inetd and xinetd
  apt:
    name:  "{{ item }}"
    state: absent
  with_items: [ openbsd-inetd, xinetd, inetutils-inetd ]
