---

- set_fact:
    svc_item: "{{ item }}"

- debug: msg="Ensure {{ svc_item.name }} is not enabled"

- name: Check if {{ svc_item.script }} exists
  stat:
    path: "{{ svc_item.script }}"
  register: svc

- name: Comment out "start" line in {{ svc_item.script }}
  lineinfile:
    path:   "{{ svc_item.script }}"
    regexp: '^start on (.*)'
    line:   '#start on \1'
    backrefs: yes
  when: svc.stat.exists
