---

- debug: msg="OS Hardening"

- include: 1_1_filesystem_configuration.yml
- include: 1_2_configure_software_updates.yml
- include: 1_3_filesystem_integrity_checking.yml
- include: 1_4_secure_boot_settings.yml   # should be optional I think
- include: 1_5_additional_process_hardening.yml
- include: 1_6_mandatory_access_control.yml
- include: 1_7_warning_banners.yml
- include: 2_2_special_purpose_services.yml
- include: 2_3_service_clients.yml
- include: 3_1_network_parameters_host_only.yml
- include: 3_2_network_parameters_host_and_router.yml
- include: 3_3_ipv6.yml
- include: 3_4_tcp_wrappers.yml
- include: 3_5_uncommon_network_protocols.yml
#- include: 3_6_firewall_configuration.yml
- include: 4_1_configure_system_accounting.yml
